// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// OrderIDGet implements GET /order/{id} operation.
//
// Returns the order details for the given order ID.
//
// GET /order/{id}
func (UnimplementedHandler) OrderIDGet(ctx context.Context, params OrderIDGetParams) (r OrderIDGetRes, _ error) {
	return r, ht.ErrNotImplemented
}
