services:
  postgres:
    image: postgres:15.1
    restart: always
    user: postgres
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "db_prod" ]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s

  order_service:
    build:
      context: ./order_service
      dockerfile: ./build/universal_service/Dockerfile
    ports:
      - "${}:${}"
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - config/.env

volumes:
  postgres_data: